name: animated_hint_textfield
description: Flutter package to animate the TextFiled hint/label text.
version: 0.0.1
maintainer: Deekshith Shetty

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


